DROP TABLE DETAILPLAN;

CREATE TABLE "DETAILPLAN" (
	"DPSQ"	NUMBER		NOT NULL,
	"DPTIME"	VARCHAR2(1000)		NOT NULL,
	"PNO"	VARCHAR2(1000)		NOT NULL,
	"DPLOC"	VARCHAR2(1000)		NULL,
	"DPCONT"	VARCHAR2(1000)		NULL
);

/*INSERT INTO "DETAILPLAN"
VALUES('1','1800','1','63빌딩',null);*/

SELECT * FROM "DETAILPLAN";
